# Generated by Django 3.2.6 on 2021-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beefy_wallet_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('creation_date', models.TimeField()),
                ('image', models.TextField()),
                ('ad_type', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
            ],
        ),
    ]
